name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Checkout tailscale repository
      uses: actions/checkout@v4
      with:
        repository: tailscale/tailscale
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: v1.80.3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag wojtekerbetowski/tailscale-mikrotik:latest

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Checkout tailscale repository
        uses: actions/checkout@v4
        with:
          repository: tailscale/tailscale
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: v1.80.3

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag wojtekerbetowski/tailscale-mikrotik:latest
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Tag and push Docker image
        run: |
          docker tag wojtekerbetowski/tailscale-mikrotik:latest ${{ github.repository_owner }}/tailscale-mikrotik:${{ steps.get_version.outputs.VERSION }}
          docker tag wojtekerbetowski/tailscale-mikrotik:latest ${{ github.repository_owner }}/tailscale-mikrotik:latest
          
          docker push ${{ github.repository_owner }}/tailscale-mikrotik:${{ steps.get_version.outputs.VERSION }}
          docker push ${{ github.repository_owner }}/tailscale-mikrotik:latest
